CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

INSERT OR IGNORE INTO Users (username, password) VALUES ("otus", "potus");

CREATE TABLE IF NOT EXISTS Sessions (
    id INTEGER PRIMARY KEY,
    user INTEGER NOT NULL,
    expires INTEGER NOT NULL,
    FOREIGN KEY(user) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Messages (
    id INTEGER PRIMARY KEY,
    user INTEGER NOT NULL,
    content TEXT NOT NULL,
    timestamp INTEGER NOT NULL,
    FOREIGN KEY(user) REFERENCES User(id) ON DELETE CASCADE
);