CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Sessions (
    id INTEGER PRIMARY KEY,
    user INTEGER,
    FOREIGN KEY(user) REFERENCES User(id) ON DELETE CASCADE
);